---
abstract: 'Create a graph from Catalyst dispatcher'
author:
  - 'Franck Cuny <franck@lumberjaph.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Dispatcher-AsGraph
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
